### ISSUE TITLE
theme not scaling correctly

### ISSUE THREAD

**Issue by rodeoss** [Saltssaumure/xp-discord-theme#10]
on my laptop i have 125% zoom and the theme doesn't seem to scale correctly as some of the borders get cut off
![image](https://github.com/Saltssaumure/xp-discord-theme/assets/134734744/174409b9-88a5-45ad-9850-f3a2d0cae641)

**Comment by Saltssaumure** [comment]
Thanks for your patience, could you provide the following info so I can try to replicate this problem?

- Operating system (Windows, MacOS, Linux, etc.)
- Client mod used (BetterDiscord, Replugged, Vencord, etc.)
- Any other CSS or themes enabled

**Comment by rodeoss** [comment]
Windows 11, BetterDiscord & I disabled all the other themes I had I believe! I was using a Laptop with 125% zoom

**Comment by Saltssaumure** [comment]
I can't seem to replicate the problem, zooming even all the way in seems to work alright here. 
![image](https://github.com/Saltssaumure/xp-discord-theme/assets/29710355/d85c5c22-5a7b-476c-8a47-d42c284f4c6c)

The members list titlebar getting cut off in your screenshot is particularly odd.
