### ISSUE TITLE
Image Preview pulls up BSOD screen

### ISSUE THREAD

**Issue by GlennSchner** [Saltssaumure/xp-discord-theme#11]
Opening an image preview will display the image preview & the BSOD screen. Clicking outside the preview will return discord to normal.
![image](https://github.com/Saltssaumure/xp-discord-theme/assets/38408292/54331d28-d25d-4109-a977-c780ff6804e6)
Using v1.9.2 of Better Discord on Stable 204204 (942e9ba) Host 1.0.9013 (32266) Windows 10 64-Bit (10.0.19045)

**Comment by Saltssaumure** [comment]
This is intentional, see #3
