### ISSUE TITLE
Image Previews get cut off

### ISSUE THREAD

**Issue by FredDoesStuff** [Saltssaumure/xp-discord-theme#12]
Whenever you open a preview for an image, if it's large enough it may get cut off your screen.
![image](https://github.com/Saltssaumure/xp-discord-theme/assets/112592014/b782e500-4931-4eb9-97b0-fd34b994d604)

**Comment by Saltssaumure** [comment]
Can't seem to replicate the problem, could you provide the following info please so I can retry?
- Client mod used (BetterDiscord, Replugged, Vencord, etc)
- Theme version
- The image you're viewing in that screenshot

**Comment by FredDoesStuff** [comment]
The client mod I am using is Vencord
I am unsure on the exact version as even in 1.3.4 they only display 1.3 for the version.
I can't seem to find the original image, but I found another one that noticeably gets cut off 
https://images-ext-1.discordapp.net/external/BaQQEGnlmRIjgkfC49Kf2ShPJ6wFAJikZc9dmKZ279M/https/media.tenor.com/AP1xprPwtvcAAAPo/gina-lestrade-toby.mp4

**Comment by Saltssaumure** [comment]
Unfortunately I still can't replicate this issue. Which plugins have you enabled? If it's a plugin conflict, I'll see if I can come up with a fix for it.

**Comment by 5hiftyyy** [comment]
I just got the same problem, also using Vencord. Figured out it's cause of the "ImageZoom" plugin, exclusive to Vencord.
Just disable it. :P

You're welcome.
