### ISSUE TITLE
I can't interact with the task bar

### ISSUE THREAD

**Issue by Maniacsan** [Saltssaumure/xp-discord-theme#16]
![Screenshot 2023-10-17 212935](https://github.com/Saltssaumure/xp-discord-theme/assets/52683414/f7085528-1619-4233-824a-8be9881b4d6a)
Whenever I press the server icon it does nothing. I also couldn't move the "Find or start a conversation" so I went into the css and moved it up.

**Comment by Saltssaumure** [comment]
Fixed.
