### ISSUE TITLE
SUGGESTION: Turn the discord loading screen into the windows XP loading screen

### ISSUE THREAD

**Issue by AW1534** [Saltssaumure/xp-discord-theme#19]
Title says it all, thought it would be cool. Not sure if its possible.

Great theme by the way, I had no clue css could even do half of this lmfao

**Comment by Saltssaumure** [comment]
Unfortunately the loading screen on opening discord is not themeable, since it loads before the client mod and theme. Thanks for the suggestion nonetheless!
