### ISSUE TITLE
Image preview error window

### ISSUE THREAD

**Issue by FlameSpyro** [Saltssaumure/xp-discord-theme#3]
Hello! Just wanted to say this theme rules! I just think there's a little error. When I look at images or an update window pops up the background becomes a fake windows error screen. Im not sure if its intentional but it just looks a little weird when trying to look at images.

**Comment by Saltssaumure** [comment]
This is intentional! If you don't want to see this, you can change both the text and the background colour in the theme settings. Click the pencil icon on the theme (in Settings > Themes) to open up the theme for editing.

**Comment by FlameSpyro** [comment]
Alrighty! Thats a really fun detail! Gave me a heart attack for a second though!
