### ISSUE TITLE
The background has changed to gray.

### ISSUE THREAD

**Issue by DetsiMies** [Saltssaumure/xp-discord-theme#4]
So it was fine for maybe 1h after I downloaded it and after that the background changed from the windows xp to a gray screen.
I tried to re install the theme but it didn't change anything it was still gray
![Sieppaa2](https://user-images.githubusercontent.com/128180446/225989673-90b2ccd3-1a47-40ad-84cb-88637aaa888f.PNG)

**Comment by Saltssaumure** [comment]
The host went down briefly but should be back now. Try restarting your computer. 

If you can see this image, then the background should be able to load:
https://saltssaumure.github.io/xp-discord-theme/img/bliss.jpg

**Comment by DetsiMies** [comment]
Sorry to say but it is not working it is still gray.
even tough I can see the image you linked.

**Comment by DetsiMies** [comment]
Yes, and re install the theme and reinstalling betterdiscord.

**Comment by Saltssaumure** [comment]
1. Clear Discord cache: https://www.howtogeek.com/686597/how-to-clear-discord-cache-files-on-desktop-and-mobile/
2. If that does not work, change the image link to https://i.imgur.com/vnvHppX.jpeg - same image but hosted on Imgur.

**Comment by DetsiMies** [comment]
Thank you. it started working after I cleared my cache
