### ISSUE TITLE
Problem with the theme

### ISSUE THREAD

**Issue by Exorcism0666** [Saltssaumure/xp-discord-theme#5]
No change due to new discord update.
![image](https://user-images.githubusercontent.com/46537034/226108586-09d5b8f1-c900-4aee-9388-72e7c5cbfa24.png)

**Comment by znopp** [comment]
Works fine for me!

**Comment by Saltssaumure** [comment]
Just tested on the same Discord and BD version - could not replicate the problem. The only difference I notice is that you're using one of the new Nitro themes. Try choosing plain dark/light mode instead, and see if that works.

**Comment by Saltssaumure** [comment]
Two things to try: 

1. Clear Discord cache: https://www.howtogeek.com/686597/how-to-clear-discord-cache-files-on-desktop-and-mobile/
2. Change the image link to https://i.imgur.com/vnvHppX.jpeg - same image but hosted on Imgur.

Let me know how you get on with that.
