### ISSUE TITLE
Bliss background image

### ISSUE THREAD

**Issue by znopp** [Saltssaumure/xp-discord-theme#6]
The background image gets slightly cropped when full-screening a screen share.

Forgive the sea of thieves content - [If you look at the background](https://cdn.znopp.pw/AHSiRNBGP5.mp4), along one of the sides, you will notice it "jumps" slightly.

The intended size of the image is, presumably, what it is when you're not full-screening a screen share, as that is the way bliss looks in settings as well.

Running BD, version 1.8.5, and the theme is version 1.3

Any and all help is appreciated!

**Comment by Saltssaumure** [comment]
The background scales to cover the entire window. When going into fullscreen, the window height slightly increases because the taskbar is hidden. Therefore, the image has to zoom in slightly to fill in that extra height.

**Comment by znopp** [comment]
Aha, okay. In that case, no issue then!

Thanks for your time :)
