### ISSUE TITLE
Small problem with User Settings

### ISSUE THREAD

**Issue by marianarfm** [Saltssaumure/xp-discord-theme#7]
Not really that big of an issue but when you go to User Settings the esc button sticks out of the border, this is on Windows 10. Happens for 'My Account' and 'Profiles' sections, is there a way to fix this? Other than that, theme works great and is very satisfying to look at 👍 
![image](https://user-images.githubusercontent.com/106042057/228285695-d9fc8859-3261-4cc8-9647-0cf3736f3b4e.png)

**Comment by Saltssaumure** [comment]
Fixed in this manner, should work on all screen widths: ![image](https://user-images.githubusercontent.com/29710355/229376941-2f8c4211-4b02-4c15-a399-bdf40c6f3648.png)
