### ISSUE TITLE
screenshare fullscreen button gets covered in group chats by member list when chat is enabled

### ISSUE THREAD

**Issue by danielah05** [Saltssaumure/xp-discord-theme#8]
under the member list is the fullscreen button, maybe moving the button to the left a bit would be a good fix for this
![DiscordCanary_qkxPbEfNdM](https://user-images.githubusercontent.com/35849198/229367363-d6ed72a8-b434-4466-a732-ad4212f732ec.png)

**Comment by Saltssaumure** [comment]
![image](https://user-images.githubusercontent.com/29710355/229378432-7a81f9c2-be40-41f6-9087-f3a2990a14d8.png)
