### ISSUE TITLE
background image won't change

### ISSUE THREAD

**Issue by theraidera** [Saltssaumure/xp-discord-theme#9]
This is the first time this happened and I don't know why it won't change. I changed the image url months ago and it was fine but now it won't change it at all. I tried deleting and reinstalling, deleting cache data, repairing better discord and installing it and nothing has worked. this was the image i use to have it as before it changed back to default.

https://wallpaperaccess.com/full/4960562.jpg

![image](https://user-images.githubusercontent.com/132900774/236807290-30a27fc0-d9fb-4ba1-85f2-0d760dba38dc.png)

**Comment by Wrathfulmaratuss** [comment]
I'm having the same exact problem.

**Comment by Saltssaumure** [comment]
I released a new version of the theme 4 days ago. If the updater in BetterDiscord doesn't have the newest version, try downloading the latest version manually. https://github.com/Saltssaumure/xp-discord-theme/releases/latest
